name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - uses: NiceLabs/automatic-github-token@v2
              with:
                  registry: true
            - name: Install
              run: npx pnpm install
            - name: Test
              run: npm run test:ci
            - name: Publish to GitHub Package (unstable)
              run: ./scripts/publish-to-github.sh
